### PR TITLE
Objects nested in Arrays are processed

### PR DESCRIPTION
**Pull request by meuserj**
I modified the recursive code so that objects nested within arrays are also processed.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks for the pr, there is an existing pr for this though. It seems that the need for this is more common than I thought. Might be good to have more unit tests before either of the array-prs is merged

**Comment by eze1981** [comment]
No merge?

**Comment by jonschlinkert** [comment]
done, released and published as 0.2.0. thanks for the reminder

**Comment by eze1981** [comment]
Thanks for your fast response!

**Pull request merged**
